# docker-compose up --build
version: '3.9'

services:
  db:
    image: postgres
    container_name: dls_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
  web:
    platform: linux/amd64
    build: .
    container_name: django_link_shortener
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/DLS
    depends_on:
      - db

volumes:
  postgres_data: